module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    colors: {
      transparent: "transparent",
      primary: "#202028",
      secondary: "#3A8CFF",
      text1: "#FFFEFF",
      text2: "#9E9FA7",
      icon: "#686875",
      success: "#80B97C",
      error: "#E15555",
      card: "#252733",
      border: "#32333B",
    },
    fontFamily: {
      gilroy: [
        "Gilroy",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Open Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      muli: [
        "Muli",
        "-apple-system",
        "BlinkMacSystemFont",
        "Segoe UI",
        "Roboto",
        "Oxygen",
        "Ubuntu",
        "Cantarell",
        "Open Sans",
        "Helvetica Neue",
        "sans-serif",
      ],
      transitionTimingFunction: {
        "expo-in-ease-out": "cubic-bezier(0.6, 0.01, -0.05, 0.95)",
      },
    },
  },
  plugins: [],
};
